components/Chat/ChatInput.tsx

The Japanese language has both kanji and hiragana, and the enter key is used to convert hiragana into kanji.
In the current implementation, `handleSend` is executed when the conversion is confirmed and starts sending messages.
When the conversion key is pressed, the message is not sent.

fix: support japanese typing

---

pages/api/chat.ts

When the message length exceeds the limit, should use the latest messages to build the context.

Correct the improper context being used when it exceeds the limit.

---

README.md

with browser-based chat UI It's not needed to provide OpenAI key to Vercel deployment

remove ENV var from vercel deployment

---

components/Chat/ChatMessage.tsx

User messages were not wrapping long lines:
This PR fixes this:

wrap user messages

---

utils/server/index.ts

Instead of 
[Error: OpenAI API returned an error]
the console will report 
[Error: OpenAI API returned an error: Too Many Requests]

Improve the error message reported to the console

---

components/Sidebar/ClearConversations.tsx

related to issue #88 
there is a small difference in the spaces of the button after confirming which leads to an unexpected animation in the sidebar settings

fix style issue after clicking on clear conversations button

---

Makefile
k8s/chatbot-ui.yaml

- add Makefile
Makefile expects .env file to be also present in on the system with the following vars - 
OPENAI_API_KEY=
DOCKER_USER=
DOCKER_TAG=
- add baseline k8s config
Baseline k8s config includes secret, deployment and service definition only. If running on local cluster, additional entries can be made to include cronjobs (e.g. update cloudflare), nginx ingress, etc.

add k8s config

---

components/Markdown/CodeBlock.tsx
styles/globals.css

Styling `CodeBlock` in ChatGPT style.
| ChatbotUI | ChatGPT |
| ----------- | ---------- |
| ![image](https://user-images.githubusercontent.com/44939683/227705080-59d49895-ca2a-495a-92b3-503520248ba8.png) | ![image](https://user-images.githubusercontent.com/44939683/227705098-ce4eaf75-cba9-451a-bf45-7c5b1da92ead.png) |

feat: codeblock styling like chatgpt

---

components/Chat/Chat.tsx
pages/index.tsx

Fixes #105 (and probably also #115)
As server configurations may change over time, relying on the 'server has API key' state stored in users' local storage could potentially become inaccurate.
- On the home page, the application now queries the server to retrieve the real state of the API key presence through [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props), which provides the new `serverSideApiKeyIsSet: boolean` prop. 
- Components now use the `serverSideApiKeyIsSet` boolean instead of the `isUsingEnv` variable. 
- Additionally, user messages have been updated to avoid confusing users with instructions related to .env.local, since they are typically not responsible for server administration.

Do not rely on user to figure out if server is configured with an api key

---

components/Chat/ChatMessage.tsx

This commit change message edit logic
**Before:**
If the message is not edited and "Edit & Submit" is pressed, then the answer will be regenerated, even if nothing has changed
**After:**
If the edited message isn't different from the original message and "Edit & Submit" is pressed, then do nothing.

fix: change message edit logic

---

next-i18next.config.js
pages/api/models.ts
types/env.d.ts
utils/app/const.ts
utils/server/index.ts

This commit modifies the OpenAI host configuration to support customization through an environment variable. This change is particularly useful in scenarios where access to the official OpenAI host is restricted or unavailable, allowing users to configure an alternative host for their specific needs.

feat: Allow customization of OpenAI host with environment variable: OPENAI_API_HOST

---

utils/app/clean.ts

While experimenting with the app code, I discovered that (accidentally) setting `conversationHistory` to `[null]` in localStorage caused the app to crash on subsequent reloads due to an error in the clean.ts module.
Currently, the only solution to this issue is for the user to clear their localStorage, which is inconvenient and not ideal.
To solve this problem, this pull request proposes skipping any corrupted conversationHistory items instead of crashing the app. This approach allows us to preserve the rest of the localStorage data and provide a better user experience.

Skip corrupted conversationHistory item to prevent app crashes

---

components/Sidebar/Conversations.tsx

sort the data, not the UI. buttons are now tab-able from the top down. 
before:
https://user-images.githubusercontent.com/5056972/227753230-6802113a-f0d3-4320-851c-80f4e94d1948.mp4
after:
https://user-images.githubusercontent.com/5056972/227753234-0ee18648-8a44-4d9f-a327-487c99535202.mp4
fixes #175

fix tab order for conversation buttons.

---

components/Chat/Chat.tsx
components/Chat/ChatMessage.tsx
components/Markdown/CodeBlock.tsx
pages/index.tsx

This commit delete `oneLight` theme from CodeBlock, so that only the dark theme remains, as in ChatGPT.
| Before | After | ChatGPT |
| ------- | ------ | --------- |
| ![image](https://user-images.githubusercontent.com/44939683/227761828-93938c37-dae8-4851-9756-b6fbcb3149e7.png) | ![image](https://user-images.githubusercontent.com/44939683/227761848-ec3cbaee-415d-43d0-9f8b-400d9ff02361.png) | ![image](https://user-images.githubusercontent.com/44939683/227761879-4b83fbaa-3440-4fc8-bb80-0a31c0ab38b7.png) |

chore: delete code light theme, like chatgpt

---

components/Chat/ModelSelect.tsx

This pull request addresses the issue of the dropdown menu text being unreadable in dark mode. The changes include adding the appropriate dark mode styles for the dropdown menu and options.

Fix unreadable dropdown menu text in dark mode

---

components/Mobile/Navbar.tsx

Fixed the overlap between the plus icon (new conversation) and prompt menu icon

fix: overlap between plus and prompt menu icon

---

.dockerignore
.github/workflows/run-test-suite.yml
.gitignore
__tests__/utils/app/importExports.test.ts
components/Chatbar/Chatbar.tsx
components/Chatbar/ChatbarSettings.tsx
components/Settings/Import.tsx
jest.config.ts
package-lock.json
package.json
pages/index.tsx
tsconfig.json
types/export.ts
utils/app/clean.ts
utils/app/importExport.ts

Fix import crash when the old format is imported.
fixes #224
fixes #145
- introduce different TypeScript types to describe the [supported export formats](https://github.com/mckaywrigley/chatbot-ui/compare/main...thomasleveil:fix-import?expand=1#diff-6e3c8c41352f867a3c08714c9e2c6aef9a56abd9e7958192092d46307813ab90R5)
- introduce [cleanData()](https://github.com/mckaywrigley/chatbot-ui/compare/main...thomasleveil:fix-import?expand=1#diff-b76d22796952ea80058b30849304cf51fbd7f7ff6fd47597976660a2565a7333R24) function that will convert any of the supported export format to the latest export format
- add unit tests 
- add github action to run the test suite and publish the test results to the PR (you might need to change _Workflow permissions_ in …

fix import 

---

components/Chatbar/Conversation.tsx
components/Folders/Chat/ChatFolder.tsx
components/Folders/Chat/ChatFolders.tsx
components/Folders/Prompt/PromptFolder.tsx
components/Folders/Prompt/PromptFolders.tsx

When tabbing though the UI, the folders, and folder editor icons are completely skipped. See
Before
https://user-images.githubusercontent.com/5056972/228050560-ae3dcdd5-1248-4b78-9714-a61ea5a3da2e.mp4
After
https://user-images.githubusercontent.com/5056972/228051676-2a91d3c7-0985-4b5f-acea-e32919c45f5b.mp4
Updated folders for Chat and for Prompts
fixes #236

convert folders to buttons & folder icons to buttons (accessibility) 

---

components/Promptbar/Prompt.tsx

when tabbing though prompts, the icons (trash, ok and cancel) are not tabbable.
before:
https://user-images.githubusercontent.com/5056972/228059945-3c1bff2b-cf44-45b3-b7c0-5bfca8391f5f.mp4
after:
https://user-images.githubusercontent.com/5056972/228059975-101a4313-654e-4752-a1eb-f9cc58c29de1.mp4
fixes: #240

update prompts to be tabbable (accessibility)

---

components/Promptbar/Promptbar.tsx

Fixed the issue with Prompt sidebar not showing on small devices

fix: prompt sidebar not showing on small devices

---

README.md
pages/api/models.ts
types/env.ts
utils/server/index.ts

See https://platform.openai.com/docs/api-reference/introduction
> For users who belong to multiple organizations, you can pass a header to specify which organization is used for an API request. Usage from these API requests will count against the specified organization's subscription quota.
We have this deployed and it's working correctly.

Allow specifying OpenAI-Organization header

---

components/Chat/ModelSelect.tsx

* adds an external link that opens in a new tab to the OpenAI account usage page
* this is useful to see how many requests have been spent and the cost
* this becomes more useful when there is a choice of models

Feature: add link to openai account usage
