- components/Sidebar/SidebarButton.tsx
- components/Sidebar/SidebarSettings.tsx
Make is look like the ChatGPT website style.
> Update settings button style

- components/Chat/ChatInput.tsx
Made it similar to openAI ChatGPT text area behavior.
> Updated ChatInput.tsx text area to autoextend for larger prompt size

- pages/_document.tsx
This will make the app appear in fullscreen when added to the iOS home screen.
> Add apple-mobile-web-app meta tags

- components/Chat/Chat.tsx
- components/Chat/ChatInput.tsx
- components/Chat/ChatMessage.tsx
- components/Sidebar/Conversations.tsx
- components/Sidebar/Key.tsx
- components/Sidebar/Search.tsx
- components/Sidebar/Sidebar.tsx
- components/Sidebar/SidebarButton.tsx
- components/Sidebar/SidebarSettings.tsx
- pages/index.tsx
related to #54 
- Introduces some UI enhancement to fix inconsistencies and match the real chatgpt.
- Fix some layout problem on different viewports that severely damage the experience
> enhance ui and fix layout problems

- components/Chat/Chat.tsx
- components/Chat/ChatInput.tsx
Make this style look like ChatGPT website.
> Update the Stop Generating button style

- components/Markdown/CodeBlock.tsx
- utils/app/data.ts
- Download icon ( using existing `@tabler/icons-react`) acting as button
- Functionality to autosuggest filename with file extension along with some random characters
- Functionality to let user edit the filename
- Download the file using blob and object url
> Download code as file button

- components/Sidebar/Sidebar.tsx
> Search within conversation.messages + conversation.name

- components/Chat/Chat.tsx
- components/Chat/ChatInput.tsx
It's a bit annoying having to click the textarea when switching conversations or starting a new conversation
> autofocus textarea

- pages/api/chat.ts
Include prompt tokens in token count. Should avoid errors like those of #102 .
> include prompt in token count

- components/Markdown/CodeBlock.tsx
show current language name on code block
P.S. Although you are using eslint, it seems that there is no automatic fixing or using prettier config to standardize code formatting, which will result in differences in code style among different people.
> feat: show language name

- components/Sidebar/Import.tsx
- components/Sidebar/SidebarButton.tsx
update SidebarButton.tsx to emit an <button> element.
refactor Import.tsx to use a SidebarButton element.
fixes #129.
> Update Sidebar Setting elements to be buttons (improve accessibility)

- components/Chat/ChatInput.tsx
This improvement adds additional information to the alert that is displayed when the user enters more characters than allowed in the rich text element. Now, the alert also shows the number of characters that the user has entered, which helps to provide clearer and more useful feedback to the use
> Added character count to alert message

- components/Chat/ChatMessage.tsx
Fix bug when button is active despite on empty message content
> fix: disable button if messageContent is empty

- components/Chat/Chat.tsx
This merge request aims to address two frustrating behaviors:
- Copy-pasting text from an ongoing response has been difficult for users, as they have to race the UI to put focus on the textfield at every response update.
- Scrolling has been somewhat laggy and unresponsive, which I suspect is due to the focus being changed.
With this update, I hope to provide a smoother user experience and improve overall usability.
> smoother autoscroll down

- components/Chat/Chat.tsx
- components/Chat/ErrorMessageDiv.tsx
- pages/api/models.ts
- pages/index.tsx
- types/index.ts
The purpose of this merge request is to improve error handling when loading models in our system. Currently, when a user enters an invalid API key, the model call fails and a generic error message is displayed. This can be frustrating for the user who is left guessing what went wrong.
- Introduced a new component and type to standardize error messages.
- Updated the error message displayed when loading models with an invalid API key to be more precise and informative.
> Precise error messages

- components/Sidebar/ClearConversations.tsx
- components/Sidebar/Conversation.tsx
- components/Sidebar/Folder.tsx
- components/Sidebar/Import.tsx
- components/Sidebar/Key.tsx
- components/Sidebar/Search.tsx
- components/Sidebar/Sidebar.tsx
- components/Sidebar/SidebarButton.tsx
- components/Sidebar/SidebarSettings.tsx
- tailwind.config.js
This commit stylizes the Sidebar view, making the font almost like in ChatGPT, and the "No conversations" block was also styled
| Before | After |
| ------- | ----- |
| ![image](https://user-images.githubusercontent.com/44939683/227765991-36d3410f-56c8-4de2-ab87-ae21138175f3.png) | ![image](https://user-images.githubusercontent.com/44939683/227766757-d0186091-e55e-464a-84e3-678ab83e19f8.png) |
> chore: change sidebar font size & style

- components/Sidebar/Conversation.tsx
- components/Sidebar/Folder.tsx
- components/Sidebar/Search.tsx
- components/Sidebar/Sidebar.tsx
- components/Sidebar/SidebarButton.tsx
- tailwind.config.js
When reducing the font size in the Sidebar, in Chat (mainly in ChatInput) the font changed to too large. This commit fixes the problem. Fixes #191
> fix: fix fonts

- .github/workflows/deploy-docker-image.yaml
Added github actions for docker image builds https://github.com/mckaywrigley/chatbot-ui/issues/92
> docker build action

- components/Chat/Chat.tsx
- components/Chat/ChatInput.tsx
- components/Chat/ModelSelect.tsx
- components/Chat/SystemPrompt.tsx
- components/Sidebar/ClearConversations.tsx
- components/Sidebar/Conversation.tsx
- components/Sidebar/Search.tsx
- components/Sidebar/Sidebar.tsx
- components/Sidebar/SidebarButton.tsx
This commit restyle some components:
- Restyle home modal (Model and System prompt) (set normal border color for light and dark theme)
- Set normal font size in sidebar (in some places the font was larger (Clear conversations > Are you sure?))
- Set normal gradient for ChatInput (fix bug when in light theme no gradient for ChatInput)
| Before | After |
| ------- | ------ |
| ![image](https://user-images.githubusercontent.com/44939683/227781351-a9e6e53c-f80f-40ff-b0ba-fb8cb8b3e0bf.png) | ![image](https://user-images.githubusercontent.com/44939683/227781369-136d04a5-0bb1-402f-868a-6c463ee8e764.png) |
> chore: restyle some components

- components/Chat/ChatMessage.tsx
- public/locales/ru/chat.json
**For translators:** need translate buttons `Save & Submit` and `Cancel` (Chat message > Edit message)
> fix: missing translation

- components/Chat/Chat.tsx
- components/Sidebar/Key.tsx
Adds some additional text:
1. Direct the user to the OpenAI website to get an API Key
2. Placeholder text on the API Key input itself
> Add some additional text for API Key

- components/Chat/Chat.tsx
- components/Chat/ChatInput.tsx
- components/Chat/ChatMessage.tsx
- components/Markdown/CodeBlock.tsx
- components/Markdown/MemoizedReactMarkdown.tsx
- utils/index.ts
Long conversations are triggering way too much re-renderings. In part because of the `<ReactMarkdown />` components.
This pull request is an effort to make scrolling long conversations fluid and pleasant.
- #184
- #205
----
**I'm open to any help or suggestions to make this happen**
> Fix rendering performances issues related to scrolling events

- pages/index.tsx
Fix the problem of zooming in the page after entering content on iPhone device #213
> Display optimization on iPhone device page

- components/Chat/Chat.tsx
- components/Sidebar/Conversation.tsx
This commit makes some small improvements:
- fix black key icon in "OpenAI Key" div
- do nothing if the name of the renamed conversation dialog contains nothing.
- fix sidebar button styles (conversation button)
- remake conversation settings
| PC | Mobile |
| --- | ------- |
| ![image](https://user-images.githubusercontent.com/44939683/227979521-44c25de7-6092-4a89-9a7b-9b52414b2a79.png) | ![image](https://user-images.githubusercontent.com/44939683/227979633-d910311a-8faf-49ad-9b1c-af110ec907fd.png) |
> chore: fix key icon, some styles and remake conversation settings

- components/Promptbar/PromptModal.tsx
- components/Promptbar/Promptbar.tsx
- pages/index.tsx
- public/locales/zh/chat.json
- public/locales/zh/promptbar.json
- public/locales/zh/sidebar.json
Update the latest translation for promptbar and fix previous translations that are no longer working.
> chore: update chinese locales

- components/Chat/ChatInput.tsx
- components/Chatbar/Conversation.tsx
- components/Folders/Chat/ChatFolder.tsx
When typing backslash followed by some characters in the chat input and then hitting entering the website would crash.
Also added some rounded corners to the folder and conversation when editing/deleting.
https://user-images.githubusercontent.com/38078427/228245721-9aab877c-186d-468b-a149-43688a5f1631.mp4
https://user-images.githubusercontent.com/38078427/228245753-55517561-f473-465b-b72e-32285ca4aee5.mp4
fixed #252
> fix: website crash when typing / followed with non prompt name

- README.md
> doc: update doc about Docker

- public/locales/es/promptbar.json
Translation to Spanish of the prompts custom template bar
> Translation to Spanish of the prompts template bar

- components/Chat/Chat.tsx
Fixed invalid Tailwind CSS overflow property
> Fix invalid Tailwind property

- components/Chat/Chat.tsx
> fix: In light mode, scroll icon is difficult to see
